version: '2'
services:
  db:
    #image: mysql
    #container_name: my
    #network_mode: bridge
    #ports:
    #  - 3308:3306
    #environment:
    #  MYSQL_ROOT_PASSWORD: oroot
    #  MYSQL_DATABASE: music
    #  MYSQL_USER: mususer
    #  MYSQL_PASSWORD: oroot

    image: postgres:12.1
    container_name: pg
    #network_mode: bridge
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=music
      - POSTGRES_USER=mususer
      - POSTGRES_PASSWORD=oroot
    restart: always
  app:
    build: .
    container_name: app
    #network_mode: bridge
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/music
    #  - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/music
      - SPRING_DATASOURCE_ROOT_PASSWORD=oroot
      - SPRING_DATASOURCE_DATABASE=music
      - SPRING_DATASOURCE_USERNAME=mususer
      - SPRING_DATASOURCE_PASSWORD=oroot
    ports:
      - 8090:8080
    #restart: always
    depends_on:
      - db
    links:
      - db