version: '2'
services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: oroot
      MYSQL_DATABASE: music
      MYSQL_USER: mususer
      MYSQL_PASSWORD: oroot
    restart: always
  app:
    build: .
    container_name: application
    ports:
      - 8090:8090
    restart: always
    #links:
    depends_on:
      - db