version: '2'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: oroot
      MYSQL_DATABASE: music
      #MYSQL_USER: root
      #MYSQL_PASSWORD: oroot
    #restart: always
  app:
    image: music
    container_name: application
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3308/music
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=oroot
      - logging.level.org.springframework.web=DEBUG
      - logging.level.org.hibernate=DEBUG
      - logging.level.root=DEBUG
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
    ports:
      - 8080:8080
    #build:
    #  context: src\main\java
    #  dockerfile: Dockerfile
    #restart: always
    depends_on:
      - mysql_db