package com.kozinets.music;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping() // This means URL's start with /demo (after Application path)
public class MusicPlayer {
        @Autowired // This means to get the bean called userRepository
        // Which is auto-generated by Spring, we will use it to handle the data
        private MusicRepository musicRepository;

        @PostMapping(path="/add") // Map ONLY POST Requests
        public @ResponseBody String addNewMusic (@RequestParam String song) {
            // @ResponseBody means the returned String is the response, not a view name
            // @RequestParam means it is a parameter from the GET or POST request
            Music music = new Music(song);
            musicRepository.save(music);
            return "Saved";
        }

        @GetMapping(path="/all")
        public @ResponseBody Iterable<Music> getAllUsers() {
            // This returns a JSON or XML with the users
            return musicRepository.findAll();
        }
}
